language: java
sudo: false # faster builds

jdk:
- oraclejdk8

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

cache:
  directories:
  - $HOME/.m2

install: true

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS todo_app;'

script:
- travis_wait 30 ./mvnw clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
- bash <(curl -s https://codecov.io/bash)