language: java
sudo: false # faster builds

jdk:
- oraclejdk8

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

cache:
  directories:
  - $HOME/.m2

install: true

before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('1') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -p1
- sudo service mysql restart
- mysql -e 'CREATE DATABASE IF NOT EXISTS todo_app;'

script:
- travis_wait 30 ./mvnw clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
- bash <(curl -s https://codecov.io/bash)